name: Deploy to Pypi

on:
  push:
    branches:
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@master

          - uses: actions/setup-python@v1
            with:
              python-version: '3.7'
              architecture: 'x64'

          - name: Build Wheel
            run: |
              rm -rf dist build kuriyama.egg-info
              python3 setup.py build sdist

          - name: Publish package
            if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
            uses: pypa/gh-action-pypi-publish@master
            with:
              user: __token__
              password: ${{ secrets.Pypi_APIToken }}